githubOrg: syntaxc4-msft
githubRepo: ContosoInsurance
markdown: kramdown
gems:
    - jekyll-gist
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
keep_files: ['app_data/jobs/triggered','app_data/jobs/continuous']